languageCode = "en"
languageName = "English"
weight = 1
title = "en-fzhnf"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/pfpv2_transparent.png"
secondaryLogo = "img/pfpv2_transparent.png"
# copyright = "Copy, _right?_ :thinking_face:"

[author]
name = "fzhnf-author"
image = "img/pfpv2.png"
headline = "A man who is the part of the whole"
bio = "Courage is a word of justice, it means the quality of mind that enables one to face apprehension with confidence and resolution"
links = [
  { x-twitter = "https://twitter.com/fzhnf_ansa" },
  { mastodon = "https://mastodin.social/@faiz_ansa" },
  { github = "https://github.com/fzhnf" },
]
