[[main]]
identifier = "twitter"
pre = "x-twitter"
url = "https://twitter.com/fzhnf_ansa"
weight = 200

[[main]]
identifier = "mastodon"
pre = "mastodon"
url = "https://mastodon.social/@faiz_AnSA"
weight = 300

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/fzhnf"
weight = 400
